require:
  - ./lib/cops/require_uuid_for_migration_references.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
