# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

gem 'authentication-zero', '~> 3.0'
gem 'bcrypt', '~> 3.1.7'
gem 'jsonapi-serializer', '~> 2.2'
gem 'pg', '~> 1.5'
gem 'pry'
gem 'puma', '>= 5.0'
gem 'rack-cors', '~> 2.0'
gem 'rails', '~> 7.1.3', '>= 7.1.3.2'

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  gem 'debug'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails', '~> 6.1.0'
end

group :development do
  gem 'annotate'
end
